### ISSUE TITLE
Help Needed: Dependencies upgrade

### ISSUE THREAD

**Issue by xomexh** [exdx/rustls-server#1]
Hi, thanks alot for this, specifically the client. 
I have been searching for a Rustls client which would allow to connect to servers with expired/self-signed certs.
This is really helpful for a small project we are working on, just that could you guide me the changes necessary for Rustls 23.0. I have tried this myself, but I'm unable to get it going.

It'd be really helpful if this would be worth the time & effort to you.

**Comment by xomexh** [comment]
Could complete it myself. Once again thanks for this, gave a good starting ground.

**Comment by exdx** [comment]
Great, glad it worked for you 👍
